/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juego.hanoi;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;;
import src.Creacion;
import src.Disco;
import src.Torre;
import src.Solucion;



/**
 *
 * @author dieez
 */
public class Juego extends javax.swing.JFrame {

    
   
/**
     * Creates new form Juego
     */
    
    private Disco disco;
    private Creacion creacion;
    private int[] torres;
    //contador interno de dsicos
    private int contador = 0;
    //los discos se almacenan en un map
    private Map map = new HashMap();
    public static int[][] puntuacionList = new int[5][2];

    public int[] getTorres() {
        return torres;
    }

    public void setTorres(int[] torres) {
        this.torres = torres;
    }
    
    /**
     *
     * @param cantMov recibe cantidad de movimientos
     * @param cantDiscos recibe cantidad de discos
     */
    public void puntMax(int cantMov, int cantDiscos){
        boolean habiaVacio = false;
        for(int i = 0; i<5 ; i++){
            if (puntuacionList[i][0] == 0){
                puntuacionList[i][0] = cantMov;
                puntuacionList[i][1] = cantDiscos;
                habiaVacio = true;
                break;
            }else if (puntuacionList[i][1] == cantDiscos){
                if (cantMov  < puntuacionList[i][0]){
                    int[] temp = new int[2];
                    temp[0] = puntuacionList[i][0];
                    temp[1] = puntuacionList[i][1];
                    puntuacionList[i][0] = cantMov;
                    puntuacionList[i][1] = cantDiscos;
                    if(i<4){
                        int[] temp2 = new int[2];
                        temp2[0] = puntuacionList[i+1][0];
                        temp2[1] = puntuacionList[i+1][1];
                        puntuacionList[i+1][0] = temp[0];
                        puntuacionList[i+1][1] = temp[1];
                    }
                    habiaVacio = true;
                    break;
                    }
                else {
                    if(i<4 && puntuacionList[i+1][0] == 0){
                        puntuacionList[i+1][0] = cantMov;
                        puntuacionList[i+1][1] = cantDiscos;
                        habiaVacio = true;
                        break;
                    }
                    }
                }
        }
        if (habiaVacio == false){
            for(int i = 0; i<5 ; i++){
            if (puntuacionList[i][1] == cantDiscos){
                if (puntuacionList[i][0] < cantMov){
                    puntuacionList[i][0] = cantMov;
                    puntuacionList[i][1] = cantDiscos;
                    break;
                    }
                }
            }
        }       
        
    }
    
    public void actualizarPunt(){
        punt1Lbl.setText("");
    }
    public Juego() {    
        
        initComponents();
        
        //da como resultado los movimentos necesarios para la solucion
        String aux = (String) opDiscos.getSelectedItem();
        ArrayList<String> lista = new ArrayList<String>();
        int discos = Integer.valueOf(aux);
              
                
        Solucion.torresHanoi(discos, 1, 2, 3,lista);
        int movimientos = lista.size(); 
        
        txtMovimientosNecesarios.setText(String.valueOf(movimientos));
        
        
        creacion = new Creacion( this.jPanel,this.txtMovimientos, this.txtMovimientosNecesarios); 
        
       
        
        
        creacion.ponerDiscos(discos);
        
        
        
        torres = new int[discos];
        
        this.setTorres(torres);
        
        //dibuja las torres
        Torre imagen = new Torre();
        jPanel.add(imagen);
        jPanel.repaint();
        
        
        
        
        //Coloca la Aplicacion al centro de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        opDiscos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMovimientosNecesarios = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMovimientos = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        punt1Lbl = new javax.swing.JLabel();
        punt2Lbl = new javax.swing.JLabel();
        punt3Lbl = new javax.swing.JLabel();
        punt4Lbl = new javax.swing.JLabel();
        punt5Lbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel.setMaximumSize(new java.awt.Dimension(600, 400));
        jPanel.setMinimumSize(new java.awt.Dimension(600, 400));
        jPanel.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        opDiscos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6" }));
        opDiscos.setToolTipText("");

        jLabel1.setText("Discos");

        jLabel2.setText("Movimientos necesarios:");

        txtMovimientosNecesarios.setText("###");

        jLabel3.setText("Movimientos actuales:");

        txtMovimientos.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Torres de Hanoi");

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Puntuciones maximas:");

        jLabel6.setText("(Menos movimientos)");

        punt1Lbl.setText("1.");

        punt2Lbl.setText("2.");

        punt3Lbl.setText("3.");

        punt4Lbl.setText("4.");

        punt5Lbl.setText("5.");

        jButton1.setText("Mostrar puntuaciones");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(opDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMovimientos)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMovimientosNecesarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel4)))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(punt1Lbl)
                    .addComponent(punt2Lbl)
                    .addComponent(punt3Lbl)
                    .addComponent(punt4Lbl)
                    .addComponent(punt5Lbl)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)
                        .addComponent(punt1Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(punt2Lbl)
                        .addGap(5, 5, 5)
                        .addComponent(punt3Lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(punt4Lbl)
                        .addGap(8, 8, 8)
                        .addComponent(punt5Lbl)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opDiscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txtMovimientosNecesarios)
                    .addComponent(jLabel3)
                    .addComponent(txtMovimientos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void caer(Disco disco,int aux){
        
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String aux = (String) opDiscos.getSelectedItem();
        ArrayList<String> lista = new ArrayList<String>();
        int discos = Integer.valueOf(aux);
              
                
        Solucion.torresHanoi(discos, 1, 2, 3,lista);
        int movimientos = lista.size(); 
        
        txtMovimientosNecesarios.setText(String.valueOf(movimientos));
        
       //limpia el panel
        jPanel.removeAll();
        jPanel.repaint();
        
       txtMovimientos.setText("0");
        
        creacion = new Creacion( this.jPanel,this.txtMovimientos, this.txtMovimientosNecesarios); 
        
        
       
        
        creacion.ponerDiscos(discos);
        jPanel.repaint();
        
        
         //dibuja las torres
        Torre imagen = new Torre();
        jPanel.add(imagen);
        jPanel.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        punt1Lbl.setText("1.Mov. " + puntuacionList[0][0] + " y " + puntuacionList[0][1] + " Discos");
        punt2Lbl.setText("2.Mov. " + puntuacionList[1][0] + " y " + puntuacionList[1][1] + " Discos");
        punt3Lbl.setText("3.Mov. " + puntuacionList[2][0] + " y " + puntuacionList[2][1] + " Discos");
        punt4Lbl.setText("4.Mov. " + puntuacionList[3][0] + " y " + puntuacionList[3][1] + " Discos");
        punt5Lbl.setText("5.Mov. " + puntuacionList[4][0] + " y " + puntuacionList[4][1] + " Discos");

    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel;
    private javax.swing.JComboBox<String> opDiscos;
    private javax.swing.JLabel punt1Lbl;
    private javax.swing.JLabel punt2Lbl;
    private javax.swing.JLabel punt3Lbl;
    private javax.swing.JLabel punt4Lbl;
    private javax.swing.JLabel punt5Lbl;
    public javax.swing.JLabel txtMovimientos;
    private javax.swing.JLabel txtMovimientosNecesarios;
    // End of variables declaration//GEN-END:variables
}
